PROJ_NAME=ocrUartHeartbeat

STANDALONE =../..

CFLAGS+=-DSMP
CFLAGS+=-Os

SRCS = $(wildcard src/*.c) \
	${STANDALONE}/common/start.S

include ${STANDALONE}/common/bsp.mk
include ${STANDALONE}/common/riscv64-unknown-elf.mk
include ${STANDALONE}/common/standalone.mk

LDSCRIPT = ${BSP_PATH}/linker/bootloader.ld
